ubuntu/adsys

- .github/workflows/auto-updates.yaml
- po/adsys.pot
- Use create-pull-request v3
- Change env variable handling due to Github change
- Create pot bootstrap
> Modernize autoupdate

- cmd/adsysd/client/policy.go
- internal/adsysservice/adsysservice.go
- internal/adsysservice/policy.go
> Update policy fixes

- .github/workflows/qa.yaml
Do not use matrix job as we are only running one version of go.
> CI: Only set go version once

- .github/workflows/adm-builds.yaml
As we can have pending updates in main and other branches (PR), ensure
we handle both case, and only update when needed.
> Update any branch independently for admx/adml based on branch name

- internal/policies/ad/adsys-gpolist
Co-authored-by: Didier Roche <didrocks@ubuntu.com>
> Properly handle inheritance

- pam/pam_adsys.c
Co-authored-by: Didier Roche <didrocks@ubuntu.com>
> Apply dconf profile to user gdm

- internal/grpc/contextidler/contextidler.go
- internal/grpc/contextidler/contextidler_test.go
Add tests for contextidler stream client interceptor
Amend comments for more clarity
> Test contextidler stream client interceptor

- .github/workflows/qa.yaml
- go.mod
- go.sum
Update go mod
Fix CI to check go mod and sum files with Go 1.16
Always run Staticcheck even if previous steps failed
> CI and go mod fixes

- cmd/integration_tests/adsys_test.go
Test errors in all commands, thanks to implemented gprc struct.
Override it for testing 0 and timeout set values.
> Integration tests for error in commands and timeout

- debian/control
- internal/adsysservice/adsysservice.go
- internal/adsysservice/adsysservice_test.go
- internal/adsysservice/export_test.go
- internal/adsysservice/internal_test.go
Implements AD server autodiscovery, using sssd
> AD server autodiscovery

- internal/adsysservice/adsysservice.go
- internal/adsysservice/adsysservice_test.go
> Fail if discovery returns an empty URL

- cmd/generate_completion_documentation.go
- internal/generators/can_modify_repo.go
- internal/generators/copy.go
- internal/grpc/logstreamer/tools.go
- internal/i18n/generate-locales.go
- pam/install.go
- tools.go
> Small misc cleanup

- cmd/integration_tests/systemdaemons/systemdaemons
- internal/consts/consts.go
- internal/policies/manager.go
- internal/policies/manager_test.go
- internal/policies/policies_test.go
> Enable gpo features ua attached

- systemd/adsys-gpo-refresh.timer
Windows clients refreshes every 90 minutes. Switch to that cadence for us as
well.
> Align refresh timer with Windows client.

- .github/workflows/adm-builds.yaml
- .github/workflows/qa.yaml
- policies/Ubuntu/lts-only/Ubuntu.adml
- policies/Ubuntu/lts-only/Ubuntu.admx
Ensure that we get the list of all supported LTSes for collecting LTS keys.
> Fix lts generation

- .github/workflows/auto-updates.yaml
Relax git rules for projecting its working tree in the container.
> Try fixing updating readme/translation in CI

- .github/workflows/qa.yaml
- debian/rules
- debian/tests/.sudo-packages
- debian/tests/control
- debian/tests/test
- internal/watcher/watcher.go
- internal/watcher/watcher_test.go
More details in the individual commit messages
> Add autopkgtest configuration for adwatchd

- internal/generators/copy.go
Looks like the sync didn't fully solve our issues. The failures are more sporadic now but they still show up from time to time.
A way of working around would have been to do something similar to 280196d0, but in our case the failing paths differ (I've seen `locale`, `polkit-1`, `zsh`, `bash-completion` until now). So instead of force-creating those directories beforehand, add a measly `time.Sleep` before exiting the generator.
I've tested this fix by triggering 3 sets of builds on LP, each one without errors.
> Fix LP builder race conditions

- .github/CODEOWNERS
This will request the review of @ubuntu/enterprise-desktop-team for every new PR that is opened which is not a draft.
> Add CODEOWNERS to adsys

- .github/dependabot.yml
Check both CI tooling and github actions versions with dependabot
> Reexpand dependabot checks

- .github/workflows/qa.yaml
Align on aad-auth.
Remove useless recursive option in grep.
> Make golang CI lint version fetching more versatile

- .github/ISSUE_TEMPLATE/bug_report.md
- cmd/admxgen/defs/categories.yaml
- cmd/admxgen/defs/mount.yaml
- policies/Ubuntu/all/Ubuntu.adml
- policies/Ubuntu/all/Ubuntu.admx
- policies/Ubuntu/lts-only/Ubuntu.adml
- policies/Ubuntu/lts-only/Ubuntu.admx
Added the required files to generate the ADM(X&L) templates for the sharing policy for the user.
DEENG-462
> ADMX and ADML generation support for the sharing policy.

- internal/testutils/files.go
- internal/testutils/golden.go
We already have some golden functionalities in testutils. We will need to group them all in a single place.
Move validation file with update and other flags.
<This is a small branch to decouple from the rest of the backend branch. More work will be needed as referenced here: https://github.com/ubuntu/adsys/issues/448>
> Add golden functionality in testutils

- cmd/adsysd/integration_tests/systemdaemons/Dockerfile
- cmd/adsysd/integration_tests/systemdaemons/build.sh
- cmd/adsysd/integration_tests/systemdaemons/systemdaemons
- internal/testutils/samba.go
Some misc fixes to get that out of the loop of our main backend branch.
This will make the whole test output also easier to read :)
> Fix tests helper and testcontainer build

- .github/workflows/qa.yaml
- cmd/adsysd/integration_tests/adsys_mount_test.go
- cmd/adsysd/integration_tests/adsys_test.go
- cmd/adsysd/integration_tests/adsysctl_completion_test.go
- cmd/adsysd/integration_tests/adsysctl_doc_test.go
- cmd/adsysd/integration_tests/adsysctl_policy_test.go
- cmd/adsysd/integration_tests/adsysctl_service_test.go
- cmd/adsysd/integration_tests/adsysctl_version_test.go
- cmd/adsysd/integration_tests/systemdaemons/run_daemons
- cmd/adsysd/integration_tests/systemdaemons/session_daemons.py
- cmd/adsysd/integration_tests/systemdaemons/vfs_mocks.py
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_anonymous_nfs_entry
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_anonymous_smb_entry
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_bad_entries
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_error
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_many_anonymous_entries
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_many_entries
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_many_nfs_entries
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_many_smb_entries
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_nfs_entry
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_smb_entry
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_unsupported_protocol
- internal/policies/mount/adsys_mount/run_test.go
- internal/testutils/rust.go
Integration tests for the user mount handler and their helper files
DEENG-464
> Integration tests user mount handler

- cmd/adsysd/integration_tests/adsys_mount_test.go
- cmd/adsysd/integration_tests/systemdaemons/vfs_mocks.py
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_ftp_entry
- cmd/adsysd/integration_tests/testdata/TestUserMountHandler/mounts_with_many_entries
Updating mocks to support the ftp protocol and adding a test case for it.
> Adding ftp protocol support for the integration tests

- internal/ad/internal_test.go
Remove usage of md5Tree in tests and replace it with our internal tool. The output is slightly different, but still readable in case of failure.
Fixes #462.
DEENG-507
> Reuse our utility function for comparing trees.

- cmd/adsysd/integration_tests/adsys_mount_test.go
- internal/policies/mount/adsys_mount/Cargo.lock
- internal/policies/mount/adsys_mount/Cargo.toml
- internal/policies/mount/adsys_mount/src/errors.rs
- internal/policies/mount/adsys_mount/src/lib.rs
- internal/policies/mount/adsys_mount/src/main.rs
- internal/policies/mount/adsys_mount/src/unit_tests.rs
Addresses some PR comments and removes a big dependency that wasn't really needed.
> Yet more rust improvements

- systemd/user/adsys-user-mounts.service
> Adding the adsys-user-mount.service file to systemd/user

- debian/control
- doc/09.-Network-shares.md
Moving curlftpfs package from a dependency to a recommendation, as it's on universe rather than main.
> Adjusting package dependencies

- .github/workflows/auto-updates.yaml
Action was failing with code 1, so I changed a few things in the bash code to reduce a few of the nested code that was there.
> Fixing failing auto update Rust dependencies action

- Cargo.lock
- Cargo.toml
- internal/policies/mount/adsys_mount/Cargo.toml
- internal/policies/mount/adsys_mount/src/logger.rs
Some fixes and improvements suggested in #444.
Thanks for the tips @liushuyu, they were all accepted and well needed.
> Rust suggestions

- .github/workflows/auto-updates.yaml
Fixing Rust auto update actions
> Fix for auto update Rust actions

- debian/changelog
> Preparing changelog for 0.10.1 release

- cmd/adsysd/client/client.go
- cmd/adsysd/client/client_test.go
- cmd/adsysd/daemon/daemon.go
- cmd/adsysd/daemon/daemon_test.go
- cmd/adsysd/integration_tests/adsys_test.go
- cmd/adwatchd/commands/main.go
- cmd/adwatchd/integration_tests/adwatchd_test.go
> Use SetArgs with variadic of strings instead of changeArgs

- debian/changelog
- debian/copyright
> Update changelog for the upcoming release

- cmd/adsysd/client/service.go
- cmd/adsysd/daemon/daemon_test.go
- cmd/adsysd/integration_tests/adsys_test.go
- internal/config/config_test.go
- internal/testutils/files.go
- internal/watcher/watcher.go
- internal/watcher/watcher_test.go
Our tests had some coverage inconsistency, despite still passing. This PR aims to fix that.
Closes #509 / DEENG-534
> Improving test consistency

- pam/pam_adsys.c
Our pam module wasn't parsing sssd.conf to check for the default_domain_suffix configuration value when setting the DCONF_PROFILE variable. This means that, for cases where the user authenticates without an explicit domain, the DCONF_PROFILE would be set to the username only, instead of user@domain.
By parsing the config value, now we are able to set the environment properly regardless of the username configuration.
Closes #686 / UDENG-331
> Updating pam module to properly set DCONF_PROFILE

- pam/pam_adsys.c
Didn't realize that my editor had intellisense disabled (which is a bad idea for writing C code without being completely fluent), so this PR fixes some things that we missed on the reviews.
> Fix a couple of C issues that weren't spotted

- .github/workflows/qa.yaml
This is the first phase of more reusable Go and general CI. Tackling Quality/Sanity checks.
UDENG-599
> Switch to reusable code quality action in CI

- cmd/adsysd/integration_tests/adsys_test.go
Docker on mantic does not take -t 0 as argument and silently ignores it (we have to wait 10s for each container to stop). It then exits with a different status code (137).
In addition, the first failure on exit calls `os.Exit(1)`, which is then leaving the other containers up.
Change the behaviour to try starting and stopping (concurrently now) all the docker containers, and accumulate returned errors to collect in the TearDown. Still provide an early exit if one of the containers failed to start.
> fix(integration-tests): docker stop behaviour

- docs/docs.go
- docs/explanation/apparmor.md
- docs/index.md
- docs/tutorial/index.md
There is no tutorial at the moment so just drop it. We will readd it later once there are some.
> docs: Removed empty tutorial section

- docs/docs.go
> docs: fix rtd root url

- docs/explanation/adsys-ref-arch.md
Fixes spelling:
* can be zoom -> can be zoomed
and punctuation:
* if not ... -> if not, ...
> docs: minor fixups for spelling and punctuation

- internal/policies/certificate/python/vendor_samba/gp/gp_cert_auto_enroll_ext.py
The last fix needed to get everything working on the certificate's autoenrollment end.
> Fix URL for getting root certificates and some bad code 
