- internal/policies/ad/ad.go
- internal/policies/ad/ad_test.go
- internal/policies/ad/export_test.go
- internal/policies/entry/entry.go
- internal/policies/policies.go
Reload the gpo list and rules from cache if the first ad connection fails
(error 2) and that we have a local cache available.
Those are the rules which will be enforced for the object.
Add tests.
> Offline mode support

- .github/workflows/qa.yaml
- debian/copyright
- go.mod
- go.sum
- internal/grpc/logstreamer/tools.go
- tools.go
Now that we migrated to Go 1.16 where go install can be run in the
project without updating the module used but respecting the set version,
run it in the project and pins the version in go.mod.
This is done by including an excluded file via tag, as represented in
https://play-with-go.dev/tools-as-dependencies_go115_en/.
> Ensure all needed tooling is in go mod

- cmd/adsysd/client/policy_test.go
- cmd/adsysd/client/testdata/golden/colorize.golden
- internal/policies/entry/entry.go
- internal/policies/entry/testdata/golden/GPO with rules
- internal/policies/entry/testdata/golden/GPO with rules and overrides, no rules processed
- internal/policies/entry/testdata/golden/GPO with rules, appending to existing treated key
- internal/policies/entry/testdata/golden/GPO with rules, override disabled key
- internal/policies/entry/testdata/golden/GPO with rules, override displayed
- internal/policies/entry/testdata/golden/GPO with rules, override hidden
- internal/policies/entry/testdata/gpos.cache
Multi-lines values were kept as multi-lines, breaking colorization and
making it hard to read.
Keep everything in a single line with \n.
> Fix multi-lines support while dumping applied policies

- debian/rules
The package fails to build in the archive with LTO enabled.
Co-authored-by: Didier Roche <didrocks@ubuntu.com>
> Disable LTO

- pam/install.go
So the dynamic symbols are correctly registered in the library.
Co-authored-by: Didier Roche <didrocks@ubuntu.com>
> Set flags in right order

- cmd/integration_tests/adsysctl_policy_test.go
- cmd/integration_tests/adsysctl_service_test.go
- cmd/integration_tests/systemdaemons/Dockerfile
- cmd/integration_tests/systemdaemons/build.sh
- cmd/integration_tests/systemdaemons/dbus.conf
- cmd/integration_tests/systemdaemons/systemdaemons.sh
- cmd/integration_tests/testdata/PolicyStatus/golden/Status offline cache
- internal/adsysservice/adsysservice.go
- internal/adsysservice/adsysservice_test.go
- internal/authorizer/authorizer_test.go
- internal/authorizer/internal_test.go
- internal/consts/consts.go
- internal/policies/ad/ad.go
- internal/policies/ad/ad_test.go
- internal/policies/ad/internal_test.go
- internal/testutils/systembus.go
- request to sssd in what status we are in
- if we are online, do the samba/ldap requests as we used to do, but with a contextual timeout.
Do not use gpolist status returned code for determining if we are offline or not. Only base our state on sssd as this is what logged it in or not.
We are doing the request everytime we want to download the GPO list, as sssd will flip status based on network connectivity change.
Note that sssd doesn’t always flip the state when going back offline having no network connected. In that case. we let gpo list script failing (either exit 2 or timing out). This will be the case only for refreshes, and the machine is already offline, but wrongly reported online. Keep thus last known good state and report the failure in logs.
> Depends on sssd offline status to try fetching the GPOs

- cmd/integration_tests/adsysctl_service_test.go
- cmd/integration_tests/testdata/PolicyStatus/golden/Invalid startup time leads to unknown refresh time
- cmd/integration_tests/testdata/PolicyStatus/golden/Invalid unit refresh time leads to unknown refresh time
- cmd/integration_tests/testdata/PolicyStatus/golden/No startup time leads to unknown refresh time
- cmd/integration_tests/testdata/PolicyStatus/golden/No unit refresh time leads to unknown refresh time
- cmd/integration_tests/testdata/PolicyStatus/golden/Status is always authorized
- cmd/integration_tests/testdata/PolicyStatus/golden/Status no user connected and no machine
- cmd/integration_tests/testdata/PolicyStatus/golden/Status offline cache
- cmd/integration_tests/testdata/PolicyStatus/golden/Status on user connected with no cache
- cmd/integration_tests/testdata/PolicyStatus/golden/Status with dynamic AD server
- cmd/integration_tests/testdata/PolicyStatus/golden/Status with empty dynamic AD server
- cmd/integration_tests/testdata/PolicyStatus/golden/Status with users and machines
The behaviour of Test.Tempdir changed in go 1.17 and now include the
name of the test and the name of the subtest. As a consequence the
golden files are different between 1.16 and 1.17 and TestServiceStatus
cannot run on both. We now strip entirely the name of the test from the
output file.
> TestServiceStatus: changed settings path

- internal/policies/ad/admxgen/dconf/testdata/golden/description_containing_deprecated_without_starting_by_it_is_not_ignored
- internal/policies/ad/admxgen/dconf/testdata/golden/description_starting_with_deprecated_is_ignored
- internal/policies/ad/admxgen/dconf/testdata/golden/description_starting_with_deprecated_mixed_case_is_ignored
- internal/policies/ad/admxgen/dconf/testdata/golden/description_starting_with_obsolete_is_ignored
Now that we add notes to dconf object, refresh golden files to add it.
> Refresh golden test files with latest dconf changes

- cmd/integration_tests/adsys_test.go
- cmd/integration_tests/systemdaemons/systemdaemons.sh
- internal/adsysservice/client.go
As we are using a local unix socket, the rights are processed at the
kernel groups level.
> Migrate to new grpc API for insecure credentials

- internal/policies/policies.go
The test was failing on my machine.
> Fix panic on some machine with zip implementation when relSrc is empty.

- cmd/integration_tests/workaround.go
No need for workaround anymore since Go 1.16.
> We can now have test-only packages.

- pam/pam_adsys.c
Both minors issues reported by Seth Arnold. Thanks!
https://bugs.launchpad.net/ubuntu/+source/adsys/+bug/1961459
> pam_adsys: Fix memory leak and identation

- internal/ad/ad_test.go
- internal/policies/policies.go
- internal/policies/policies_test.go
- internal/policies/scripts/scripts.go
- internal/policies/scripts/scripts_test.go
- internal/policies/testdata/golden/saveassetsto/chown directories and files when requested/GPT.INI
- internal/policies/testdata/golden/saveassetsto/chown directories and files when requested/random/asset1.img
- internal/policies/testdata/golden/saveassetsto/chown directories and files when requested/random/asset2.img
- internal/policies/testdata/golden/saveassetsto/chown directories and files when requested/random/subdir/asset-in-subdir
- internal/policies/testdata/golden/saveassetsto/chown directories and files when requested/scripts/script-no-extension
- internal/policies/testdata/golden/saveassetsto/chown directories and files when requested/scripts/script-other.sh
- internal/policies/testdata/golden/saveassetsto/chown directories and files when requested/scripts/script-simple.sh
- internal/policies/testdata/golden/saveassetsto/chown directories and files when requested/scripts/subdir/script-in-subdir.sh
Fix potential security race with user/gid reset
Only chown to uid and gid when creating directories and any fd before closing we are in control of.
This impacted the API for passing desired uid and gid.
Remove the final recursive reset.
Rework chowning when needed. Set -1 to be API compliant for no change.
> Fix chown scripts

- internal/testutils/samba.go
Because obviously an "Improved command line user experience" (from the
Samba 4.15.0 release notes) means incompatible changes, adsys currently
ftbfs becaus smbd no longer takes -S / --log-stdout as an option, it's
now --debug-stdout.
> internal/testutils: invoke smbd with option accepted by 4.15+

- internal/config/config_test.go
Ensure the files are committed on disk for the refresh to be taken into
account.
This is in hope that on VM tests, we get less time-sensitive failures.
> Try reducing race conditions when testing configuration change

- internal/testutils/samba.go
When killing smbd process, on ppcel64, stderr was not closed, causing
the tests to hang forever.
> Workaround tests hanging on ppcel64

- internal/config/config_test.go
This test is still failing randomly in the archive or in autopkgtests on
armhf and arm64.
Change thus the approach to define phases:
- First phase is initial configuration set
- Second optional phase is a configuration change for some tests
- Third phase is the "done" one.
This way, we control the amount of callbacks we are interested in and
picking, discaring the unwanted multiple inotify event for the same
write on disk.
It seems to make the flaky failure (which only impacts tests, as in a
real system, we are interested even in no-op changes) go away on arm64
after multiple attempts.
> Try fixing flaky "pick up config changes" tests

- internal/ad/admxgen/admxgen.go
- internal/ad/admxgen/common/common.go
strings.Title() is deprecated in Go 1.18, switch to golang.org/x/text ini
adm* code generation.
Co-authored-by: Gabriel Nagy <gabriel.nagy@canonical.com>
> Switch Title generation to non deprecated function

- internal/policies/dconf/dconf.go
Fix dconf file permissions to be user readable, so that gsettings can
access and read it.
> Make dconf files readable to user

- debian/install
- systemd/run-adsys.mount
/run is now noexec on Ubuntu. Ensure that we can execute the scripts in
/run/adsys subdirectories. The scripts mecanism has been reviewed by the
security team, so we can reset them as executable.
> Ensure we can execute machine and user scripts

- cmd/adsysd/client/client.go
- cmd/adsysd/daemon/daemon.go
We always set the verbosity the same way between the two binaries. This
ensure consistency.
> Align setting verbosity between admxgen and adsys*

- .github/workflows/sync-gh-jira.yaml
Use a default "jira" tag to import bugs to our Jira instance.
> Enable github to jira bug synchronization

- internal/config/config.go
- internal/config/config_test.go
In adwatchd we would like to use the executable directory as the default config path.
Update the config API to add the executable path to the config search path, after all the other paths.
> Add the current executable dir to the config load path

- cmd/adsysd/client/client.go
- cmd/adsysd/daemon/daemon.go
- internal/cmdhandler/cmdhandler.go
- internal/config/config.go
- internal/config/config_test.go
Previously we made the assumption that the command passed to config.Init is always the root command. This works well when the config flag is persistent and defined on the root command.
Update the config initialization API to also work with cases where we don't want to define a persistent root flag and only have the `--config` flag on subcommands.
It is the responsibility of the caller to ensure that the correct Cobra command is passed to config.Init.
> Allow config.Init to work on non-persistent flags

- debian/control
- debian/rules
- debian/tests/control
- debian/tests/test
- internal/generators/copy.go
Opening this for early discussion as we still have to fix the failing `armhf` [build](https://launchpadlibrarian.net/610641368/buildlog_ubuntu-kinetic-armhf.adsys_0.8.6ubuntu12_BUILDING.txt.gz):
```
In file included from src/github.com/ubuntu/adsys/vendor/github.com/mvo5/libsmbclient-go/libsmbclient.go:17:
/usr/include/samba-4.0/libsmbclient.h:84:13: error: size of array 'smbc_off_t_should_be_at_least_64bits_use_LFS_CFLAGS' is too large
84 | typedef int smbc_off_t_should_be_at_least_64bits_use_LFS_CFLAGS[sizeof(off_t)-7];
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
------------------------------------
- build/ship adwatchd on amd64 and arm64, other architectures are not supported by go
- build adwatchd with PIE on amd64 as other architectures are not supported
- …
> Update packaging to work across architectures

- .github/workflows/sync-gh-jira.yaml
The ubuntu/sync-issues-github-jira action can now convert GitHub Markdown to JIRA Markdown. However, this is only supported starting with Ubuntu 22.04 which is not yet `ubuntu-latest`.
Explicitly request `ubuntu-22.04`. We can revert this change when GitHub changes `ubuntu-latest` to point at `ubuntu-22.04`.
> Bump runner version for the Jira sync workflow

- internal/ad/ad.go
- internal/ad/internal_test.go
- internal/consts/consts.go
- internal/policies/apparmor/apparmor_test.go
- internal/policies/apparmor/testdata/golden/TestApplyPolicy/error_on_read-only_.new_directory/etc/apparmor.d/adsys/machine.new/nested/usr.bin.baz
- internal/policies/apparmor/testdata/golden/TestApplyPolicy/error_on_read-only_.new_directory/etc/apparmor.d/adsys/machine.new/nested/usr.bin.nested.absent
- internal/policies/apparmor/testdata/golden/TestApplyPolicy/error_on_read-only_.old_directory/etc/apparmor.d/adsys/machine.old/nested/usr.bin.baz
- internal/policies/apparmor/testdata/golden/TestApplyPolicy/error_on_read-only_.old_directory/etc/apparmor.d/adsys/machine.old/nested/usr.bin.nested.absent
- internal/policies/apparmor/testdata/golden/TestApplyPolicy/error_on_read-only_machine_directory/etc/apparmor.d/adsys/machine/nested/usr.bin.baz
- internal/policies/apparmor/testdata/golden/TestApplyPolicy/error_on_read-only_machine_directory/etc/apparmor.d/adsys/machine/nested/usr.bin.nested.absent
- internal/policies/privilege/privilege_test.go
- internal/testutils/files.go
A read only directory should have 555, so that we can still walk into it. This was triggering false positive when testing for write errors.
Fix some tests, comment some for investigation and append some cleanups that were hanging in the tree for long.
> Fix test helper permission when making directory RO

- internal/policies/scripts/scripts.go
- internal/policies/scripts/scripts_test.go
Ensure we always have a machine directory created by the script manager (it should be similar to all managers using those directories).
Fix the localhost up to date state in integration tests to always have the empty user directory. This is consistent with the managers creation state. Refresh the golden files for them.
> DEENG-487 Update scripts manager creation and golden files consistency

- internal/policies/mount/adsys_mount/run_test.go
- internal/testutils/files.go
- internal/testutils/rust.go
Hook up running rust tests from go test command, with proper detection and cache handling.
> Allow running mount_handler tests as part of go test

- internal/testutils/pythoncoverage.go
The new python coverage package changed its way to name converted coverage file in -d when annotating.
Adapt to the new convention without importing the python logic which may change.
This still works on files without path.
> Fix python coverage in integration tests

- internal/testutils/coverage.go
- internal/testutils/pythoncoverage.go
Those functions will be used by Rust and Python coverage all together.
> Factorize some coverage testutils functions

- cmd/adsysd/integration_tests/adsysctl_policy_test.go
- internal/ad/internal_test.go
- internal/testutils/coverage.go
- internal/testutils/pythoncoverage.go
Encapsulate the tracking methods fully in testutils. The API is minimized and don’t rely on the consumer to pass the correct filename anymore, as it’s internal.
Adapt python coverage to this new API.
Simplify the collect and make it (if needed) able to recollect after first tracking.
Add many more comments on API documentation.
> Refactor tracking and generating coverage files

- .github/workflows/qa.yaml
- internal/policies/mount/adsys_mount/run_test.go
- internal/policies/mount/adsys_mount/src/coverage.go
- internal/testutils/files.go
- internal/testutils/rust.go
* Hook up running rust tests from go test command, with proper detection and cache handling.
* Add Rust -> Go coverage convertion support
Similarly to python, add helpers for Rust code coverage.
Refactor some helper functions to minimize the API surface and make it more idiomatic.
* Add coverage to Rust mount handler
In addition to call the coverage file, we need to mark src/ as a Go package for the Go coverage tool picking it up.
Note that this has been tested with Rust modules in subdirectories of src/ too.
DEENG-513
> Rust tests with coverage and CI

- cmd/adsysd/integration_tests/adsysctl_policy_test.go
- internal/testutils/coverage.go
- internal/testutils/pythoncoverage.go
* Prevent coverage tracking to be called twice in the same test
* Annotate python coverage file in a subdirectory
* Move python file tracking per test
DEENG-531
Fixes: #500
> Stabilize integration test coverage

- .github/workflows/adm-builds.yaml
- .github/workflows/qa.yaml
set-output is going to be deprecated as per
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/. Use the new syntax.
> Fix output github action deprecation warning

- cmd/adsysd/client/policy.go
- internal/ad/ad.go
- internal/ad/ad_test.go
- internal/ad/internal_test.go
- internal/adsysservice/adsysservice.go
- internal/adsysservice/policy.go
- internal/policies/manager.go
- internal/policies/manager_test.go
Fixes a bug where FQDN hostnames were being treated as the account name to be queried for when searching for GPOs. Addresses issue #523.
DEENG-538
> Improvements on the handling of hostnames to account for FQDN

- debian/control
I might be completely wrong, but I think that we only need to add some dependencies to the package and then the packaging for the system mounts is done.
> Adding cifs-utils and curlftpfs as dependencies for the adsys package

- .github/workflows/auto-updates.yaml
- debian/control
Adding action to auto update the XS-Vendored-Sources-Rust field in debian/control.
Some lines are commented and changed in order to test the action behavior, but will be fixed before merging.
Readme checks are failing because of the absence of https://github.com/ubuntu/adsys/commit/573eb07bc4729e8bb3a5429b19f09cbe509e8948, which fixed the dependencies of the action (will stop once the branch is rebased onto main).
> Vendored sources autoupdate action

- debian/adsys.lintian-overrides
- debian/rules
Instead of completely removing the lockfile, we only move it instead. This still tricks Cargo and makes it build using the checksums of our local vendored dependencies. After the build process (for both the binary and the tests), we restore the lockfile to the upstream version.
> Workaround Cargo.lock removal

- go.mod
- internal/config/watchd/testdata/TestWriteConfig/golden/with_nested_config_path
- internal/config/watchd/testdata/TestWriteConfig/golden/with_relative_config_path
- internal/config/watchd/watchd.go
- internal/watchdtui/testdata/TestInteractiveInput/golden/submit_with_default_config.yaml
- internal/watchdtui/testdata/TestInteractiveInput/golden/submit_with_directory_as_config_input.yaml
- internal/watchdtui/testdata/TestInteractiveInput/golden/submit_with_dot_directories_is_normalized.yaml
- internal/watchdtui/testdata/TestInteractiveInput/golden/submit_with_double_dot_directories_is_normalized.yaml
- internal/watchdtui/testdata/TestInteractiveInput/golden/submit_with_duplicate_directories.yaml
- internal/watchdtui/testdata/TestInteractiveInput/golden/submit_with_fresh_config_in_current_directory.yaml
- internal/watchdtui/testdata/TestInteractiveInput/golden/submit_with_fresh_config_in_nested_directory.yaml
- internal/watchdtui/watchdtui_test.go
Right now, we are using two YAML packages
1. gopkg.in/yaml.v2
2. gopkg.in/yaml.v3
We can keep only the latest `gopkg.in/yaml.v3` package.
> Replace `gopkg.in/yaml.v2` with `gopkg.in/yaml.v3`

- .github/workflows/auto-updates.yaml
- .gitignore
- debian/cargo-checksum.json
- debian/rules
This pull request utilizes a behavior in the Debian Cargo wrapper to workaround several issues where the Rust crate can not be compiled correctly due to non-overridable options in the said wrapper.
Also, use the real checksum in the facade manifest to avoid the need for updating `Cargo.lock` file.
> Clean-up the packaging scripts in `user-mount-handler`

- internal/config/config.go
- internal/config/config_test.go
Viper relies on fsnotify to trigger a config update. However, the fsnotify docs state that the Write event is also triggered by truncating the file. This means that the update callback was being called too soon and we were unmarshaling the file contents before they were properly written.
To avoid this problem, the os.WriteFile call had to be replaced and now we manually open the file, write to it and then close it to properly flush the changes and only then have the callback triggered.
DEENG-607
> Replacing os.WriteFile after init in the config tests

- .github/workflows/auto-updates.yaml
- debian/cargo-checksum.json
As we spotted in aad-auth, the update-fake-checksum job had some issues and we had to rewrite it. This PR applies the same changes made in aad-auth to adsys, to avoid future problems. More detailed information can be seen on the commit messages and on https://github.com/ubuntu/aad-auth/pull/140
> Updating Rust auto-update actions

- .github/workflows/auto-updates.yaml
- debian/cargo-checksum.json
- debian/rules
Our previous strategy of copying a fake checksum file to the problematic crate was unsustainable, since dependencies can change (either directly or indirectly) when updating our code (or our dependencies version) and new crates with .a files could emerge.
To avoid such problems in the future, the idea is to simplify the checksums when building the source package. This way, we can still use the general crate checksum while also being able to build the package without the .a files.
> Fixing crates checksum issue

- internal/policies/apparmor/apparmor.go
- internal/policies/dconf/dconf.go
- internal/policies/gdm/gdm.go
- internal/policies/manager.go
- internal/policies/mount/mount.go
- internal/policies/privilege/privilege.go
- internal/policies/scripts/scripts.go
When creating the mount policy manager, we realized that we needed a defined way of handling errors in the managers. Which errors should prevent authentication? Which errors should only be warned to the user?
After some discussion, we defined an expected general behavior that all managers should have and this must documented on the general manager, defined in manager.go
Closes #528
DEENG-539
> Adding guideline docs to policy managers

- .github/workflows/qa.yaml
We were using `covermode=count` in `adsys`, which isn't what we really want. This PR changes the `covermode` to `set`, which basically translates to `true` or `false` if the line is covered or not. Could help with #509.
DEENG-639
> Changing covermode to set in qa.yaml

- internal/policies/apparmor/apparmor.go
- internal/policies/dconf/dconf.go
- internal/policies/gdm/gdm.go
- internal/policies/manager.go
- internal/policies/mount/mount.go
- internal/policies/privilege/privilege.go
- internal/policies/proxy/proxy.go
- internal/policies/scripts/scripts.go
Added a mutex map to the One Manager to sync the applying process of the multiple policy managers. We don't want to run multiple policy managers concurrently for the same object, so if we start applying a policy to the object, the other managers should wait for it to finish before starting their applying process to that object.
Closes #427 / DEENG-644
> Updating sync strategies for the policy managers

- pam/pam_adsys.c
In the `pam_adsys.c` file, we were using tabs for indentation. This replaces them with spaces to avoid future problems.
> Replacing tab indentation in `pam_adsys.c`

- .clang-format
- .github/workflows/qa.yaml
- internal/ad/backends/winbind/mock/libwbclient_mock.c
- pam/pam_adsys.c
As discussed, we decided to add a linter to C source files in our projects.
This PR adds a .clang-format file to the root directory and applies the linter to our C files.
> Adding clang-format configuration and applying the linter to C source files

- systemd/user/adsys-user-mounts.service
Having `WantedBy=default.target` for the user mounts service was causing it to be installed under `graphical.target`, which is too early for `gvfs-daemon.service` to have the correct environment.
Switching to `WantedBy=graphical-session.target` delays the unit starting process a little bit and ensures we'll have the Kerberos ticket available at `KRB5CCNAME` necessary to handle authenticated mounts.
UDENG-518
> Fix [Install] target of adsys-user-mounts.service

- debian/changelog
Opening the PR so that we can iterate over it and see what else needs to go in and go out.
> Prepare changelog for 0.12.0 release

- internal/smbsafe/smbsafe_test.go
- Increase sleep time to be a little more than the time we expect the routine to wait to prevent some time mismatches.
- Change type conversion to uint64 rather than int64 to avoid overflows.
> Address a few issues in smbsafe_test.go

- cmd/admxgen/defs/categories.yaml
- cmd/admxgen/defs/dconf.yaml
- policies/Ubuntu/all/Ubuntu.adml
- policies/Ubuntu/all/Ubuntu.admx
- policies/Ubuntu/lts-only/Ubuntu.adml
- policies/Ubuntu/lts-only/Ubuntu.admx
Adds policy to also configure the background picture for the dark mode, which uses a different key: picture-uri-dark.
Closes #701 / UDENG-340
> Update policy definitions to include dconf key for dark mode background

- .github/workflows/adm-builds-fail.md
- .github/workflows/adm-builds.yaml
ADMX/L build failures are sometimes hard to spot and this isn't great. Opening an issue and syncing it to Jira will help us to notice those failures and to start handling them.
Example of issue opened by the action: #756. (It was opened before fixing the job order and without the Jira tag to avoid cluttering Jira with test issues)
UDENG-990
> Open issue when ADMX/L builds fail

- .github/dependabot.yml
Having the scopes defined in the commit message was adding a "(deps)" tag to it, but that's exactly the purpose of the prefixes that we already add.
> ci: Remove scopes from dependabot config

- docs/conf.py
Some Ubuntu websites are unstable so retry up to 3 times.
> fix(docs): Retries link checker on failure

- go.mod
`govulncheck` was updated and now some CI tests are failing due to security vulnerabilities in some standard library packages. This can be fixed by bumping the required go version to 1.21.4, which is done in this PR.
> deps(go): bump go version to 1.21.4

- docs/how-to/set-up-adwatchd.md
Replaced "ProgramData" with "Program Files" to follow MS documentation.
Closes: #834 
UDENG-1699
> Fix installation path of adwatchd

- docs/Makefile
- docs/custom_conf.py
- docs/make_toctree.sh
Run a pre-hook to create index file in policy reference.
To be able to list the whole policy reference definition, we needs index file for each category.
Create them on the fly, listing the reference policies generated in the reference destination directory, before generating the finale documentation.
-----
UDENG-1450
> docs: sphinx reference doc index generation

- cmd/adsysd/daemon/daemon_test.go
If a `require` check fails outside of the main goroutine, it causes a panic.
This test is a common pattern in our projects, so I went looking for it after having golangci-lint warn about it in Ubuntu Pro for WSL.
> fix(test): Fix require outside of main goroutine

- cmd/adsysd/client/policy_test.go
- cmd/adsysd/integration_tests/adsys_test.go
- cmd/adsysd/integration_tests/adsysctl_policy_test.go
- cmd/adsysd/integration_tests/adsysd_scripts_test.go
- internal/ad/admxgen/admxgen_test.go
- internal/ad/admxgen/dconf/dconf_test.go
- internal/ad/admxgen/internal_test.go
- internal/ad/backends/sss/sss_test.go
- internal/ad/backends/winbind/winbind_test.go
- internal/ad/internal_test.go
- internal/config/watchd/watchd_test.go
- internal/policies/apparmor/apparmor_test.go
- internal/policies/certificate/certificate_test.go
- internal/policies/dconf/dconf_test.go
- internal/policies/gdm/gdm_test.go
- internal/policies/manager_test.go
- internal/policies/mount/internal_test.go
- internal/policies/mount/mount_test.go
- internal/policies/policies_test.go
- internal/policies/privilege/privilege_test.go
- internal/policies/scripts/scripts_test.go
- internal/testutils/golden.go
- internal/watchdtui/watchdtui_test.go
Use TESTS_UPDATE_GOLDEN to update golden files
This will allow to update all golden files in one go, without having to endure the update flag installation and potential warning that the flag is not supported in some packages.
Align check if update flag is enabled on other projects.
UDENG-2468
> feat(tests): use an env variable to update golden files

- .github/workflows/qa.yaml
They are requiring a zip file instead of the xml directly. Ship both of it so that we still link the xml directly from README.
UDENG-2555
> feat(coverage): ship Corbertura assets as a zip for our partner

- docs/.custom_wordlist.txt
- docs/index.md
- docs/tutorial/certificates-autoenrolment.md
- docs/tutorial/index.md
The ADSys documentation contains one tutorial currently.
It is only presented in video format, and generally there should be a text-based version of any tutorial that is included in our documentation.
This PR provides a text-based version of the video tutorial. It attempts to adhere closely to the video content while adding/subtracting as necessary for clarity.
Some minor rewording is also done to the main and tutorial index pages to improve clarity and consistency.
UDENG-3603
> docs: add text version of certificates tutorial

- internal/ad/backends/sss/sss.go
- internal/ad/backends/sss/sss_test.go
- internal/ad/backends/sss/testdata/TestSSSD/configs/EXAMPLE.COM
- internal/ad/backends/sss/testdata/TestSSSD/golden/ignore_upper_cases_in_domain_name
Use `ini.InsensitiveLoad` instead of `ini.Load` when reading `sssd.conf` to allow for both `domain/DOMAIN.COM` and `domain/domain.com` formatting.
Closes #1054 
UDENG-3725
> Ignore casing in domain/ section of sssd.conf

- pam/pam_adsys.c
This function is supposed to transform a domain.com\user username to the @ format (i.e. user@domain.com). However, it was leaving the parsed username with bad characters in the end (maybe an off behavior from strncpy or something wrong in our string manipulation). Switching to `strncat` ensures we concatenate only what we want at the end of the string.
UDENG-4314
> Fix username parsing in PAM's slash_to_at_username

- debian/changelog
```
adsys (0.15) oracular; urgency=medium
* Fix DCONF policy manager removing user DB on empty policy (LP: #2078245)
* Ignore casing in domain/ section of sssd.conf (LP: #2078246)
* Fix parsing of slash usernames (i.e. domain\user) (LP: #2078247)
* Fix errno in get_ticket_path()
* Remove XML declaration from glib schemas
* Bump Go version to 1.23
* CI and quality of life changes not impacting package functionality:
- Integrate repo with TiCS quality assessment
- Switch documentation spellchecking to en-GB 
- Add text version of certificates tutorial 
- Additional code coverage through more testing 
- Improvements to the e2e test environment
* Bump dependencies to latest: 
- jidicula/clang-format-action
- github.com/charmbracelet/bubbles 
- github.com/charmbracelet/bubbletea 
- …
```
> Release 0.15

- cmd/adsysd/main_test.go
- cmd/adwatchd/main_test.go
The release version has a real version number and not dev. Just ensure something is printed in the version string.
> Fix version based tests on released version

- cmd/adsysd/daemon/daemon.go
- conf.example/adsys.yaml
- docs/.custom_wordlist.txt
- docs/reference/adsys-daemon.md
- internal/ad/ad.go
- internal/adsysservice/adsysservice.go
- internal/consts/consts.go
Hello, I hope you are good.
Added a `--gpo-list-timeout` flag and a `gpo_list_timeout` configuration parameter on the adsys daemon.
By default, the GPO list timeout is fixed to 10 seconds. If the GPO list python script takes more than 10 seconds it's killed by the timeout. However, there might be scenarios where 10 seconds might not be enoguth. In our use case, the GPO list procedure finishes around 15 seconds in average. 
Have a wonderful day ^^
> Add GPO list daemon timeout option

- internal/adsysservice/adsysservice.go
As the CI couldn’t run on forked repo due to env variable capture, fix now this linting issue.
> Fix minor linting issue

- .github/workflows/qa.yaml
Put the runner here instead of GH project config as it’s not available to the forked repositories otherwise when submitting PRs: https://github.com/orgs/community/discussions/44322.
Workflow environements don’t work either.
> Ensure CI can run on forked repo PRs

- .github/workflows/qa.yaml
#1138 replaced the `file` parameter with `files`, so we need also to update it.
> fix: Replace deprecated CI parameter

- go.mod
- tools/go.mod
We have a mismatch between the versions listed in the project root and the tools/ directory. Let's keep it synced.
> Sync Go versions declared in the project

- internal/consts/consts.go
- internal/policies/manager.go
- internal/policies/manager_test.go
- internal/policies/privilege/export_test.go
- internal/policies/privilege/privilege.go
- internal/policies/privilege/privilege_test.go
- internal/policies/testdata/TestApplyPolicies/golden/succeed/etc/polkit-1/rules.d/00-adsys-privilege-enforcement.rules
- internal/policies/testdata/TestApplyPolicies/golden/succeed_if_checking_for_backend_online_status_returns_an_error/etc/polkit-1/rules.d/00-adsys-privilege-enforcement.rules
We were not overriding the polkit system reserved dir for the tests here, so it would cause a failure on launchpad builds (which work under a different user with different permissions).
> Fix internal/policies/manager tests

- debian/changelog
adsys (0.16.0) plucky; urgency=medium
* Bump minimum Go version to 1.22
* Run certificates auto enroll script with debug enabled based on daemon
verbosity
* Add support for Polkit >= 124
* Refresh policy definition files to support latest Ubuntu releases
* CI and quality of life changes not impacting package functionality:
- Enable CI to run on pull requests from adsys forks
- Update links to new server documentation
* Bump dependencies to latest:
- github.com/charmbracelet/bubbles
- github.com/charmbracelet/bubbletea
- github.com/charmbracelet/lipgloss
- github.com/fatih/color
- github.com/leonelquinteros/gotext
- github.com/pkg/sftp
- github.com/stretchr/testify
- golang.org/x/net
- golang.org/x/sys
- golang.org/x/text
- golang.org/x/crypto
- google.golang.org/grpc
- …
> Release 0.16.0

- debian/control
- go.mod
- tools/go.mod
We now rely on Go >= 1.22.7, but Jammy and Noble versions (for the `golang-1.22-go` package) only go up to 1.22.2, which means we would be unable to build for those distributions. Since those versions now also have `golang-1.23-go` available, let's use that package instead (this part of the change will only be noticeable on the SRUs) and bump the version here to ensure we are covered by our CI.
> Bump Go to 1.23

- docs/custom_conf.py
- docs/diagrams/arch-adsys.mmd
- docs/diagrams/arch-sssd.mmd
- docs/diagrams/arch-state.mmd
- docs/diagrams/readme.md
- docs/explanation/adsys-ref-arch.md
- docs/explanation/index.md
- docs/how-to/set-up-ad.md
Adds an architecture explanation for ADSys to the documentation, including a discussion of SSSD's role.
Mermaid is used for rendering the diagrams, which required an extension.
Other minor changes:
- Slightly rewritten landing page for Explanations
- Formatting, spelling
UDENG-5808
> docs: ADSys arch explanation

- cmd/adsysd/integration_tests/adsysctl_doc_test.go
PR #1177 introduced a new .md file in docs/diagrams. However, this file is a guide to how to use the diagram tooling rather than adsys documentation, so we need to ignore that directory as well in the test checks.
> Fix integration test `TestDocCompletion`

- debian/rules
- e2e/scripts/patches/focal.patch
- e2e/scripts/patches/jammy.patch
- go.mod
- tools/go.mod
The crypto/x509 package has a vulnerability issue in Go 1.23.1, as can be seen in: https://github.com/ubuntu/adsys/actions/runs/13009232065.
To avoid it, we should bump the toolchain version.
> Bump Go toolchain version to 1.23.5

- internal/policies/certificate/cert-autoenroll
- internal/policies/certificate/certificate.go
- internal/policies/certificate/python/vendor_samba/gp/gp_cert_auto_enroll_ext.py
- internal/policies/certificate/testdata/TestCertAutoenrollScript/golden/enroll_with_empty_advanced_configuration
- internal/policies/certificate/testdata/TestCertAutoenrollScript/golden/enroll_with_simple_configuration
- internal/policies/certificate/testdata/TestCertAutoenrollScript/golden/enroll_with_simple_configuration_and_debug_enabled
- internal/policies/certificate/testdata/TestCertAutoenrollScript/golden/enroll_with_valid_advanced_configuration
- internal/testutils/admock/vendor_samba/gp/gp_cert_auto_enroll_ext.py
This PR handles some issues encountered during certificate auto-enrollment on environments with multiple domains. Specific details for the fixes are listed on their respective commit messages, so I highly recommend looking at those.
Closes #1108 
UDENG-4835
> Certificate enrollment: Fixes for LDAP searches and for some issues with multiple domain environments

- debian/changelog
adsys (0.16.2) plucky; urgency=medium
* Fixes and improvements to certificate autoenrollment
- Improve log messages to help understand issues and failures
- Fix LDAP queries on multiple domains environments
- Allow default behavior to get supported certificate templates
to be overriden through cepces configuration
> Release 0.16.2

- docs/.custom_wordlist.txt
- docs/.sphinx/spellingcheck.yaml
- docs/custom_conf.py
- docs/explanation/adsys-ref-arch.md
- docs/explanation/apparmor.md
- docs/explanation/certificates.md
- docs/explanation/dconf.md
- docs/explanation/network-shares.md
- docs/explanation/proxy.md
- docs/explanation/scripts.md
- docs/how-to/join-ad-manually.md
- docs/how-to/set-up-ad.md
- docs/how-to/set-up-adsys.md
- docs/how-to/set-up-adwatchd.md
- docs/how-to/use-gpo.md
- docs/index.md
- docs/reference/adsys-daemon.md
- docs/reference/adsysctl.md
- docs/tutorial/certificates-auto-enrollment.md
- docs/tutorial/index.md
* Changes default spellchecker from UK to US in line with recent Canonical policy
* Fixes spellcheck errors from UK spellings and updates custom wordlist where needed
* Reactivates spellchecker on reference docs
UDENG-5698
> docs: Change spelling to US

- go.mod
- tools/go.mod
Fixes vulnerability #1: GO-2025-3447
Timing sidechannel for P-256 on ppc64le in crypto/internal/nistec
More info: https://pkg.go.dev/vuln/GO-2025-3447
Standard library
Found in: crypto/internal/nistec@go1.23.5
Fixed in: crypto/internal/nistec@go1.23.6
Platforms: ppc64le
> Bump Go toolchain to 1.23.6

- docs/custom_conf.py
- docs/explanation/index.md
- docs/how-to/join-ad-installation.md
- docs/how-to/join-ad-manually.md
- docs/how-to/set-up-ad.md
- docs/how-to/set-up-adsys.md
- docs/index.md
Various changes to improve the user experience when finding and visiting the docs for the first time:
* Homepage: decreased repetition of content; made less Desktop-specific; improved flow and organisation; linked to specific content from Diataxis cards; converted grid items to cards for improved padding between items
* Made page titles less generic: some pages were made more discoverable/searchable by giving them more descriptive titles
* Fixed title: title(s) at top of the documentation should refer to the name used to identify the feature -- ADSys -- rather than its role or function, which is already specified in the main text
* Edit button: added an edit button at the top of the page to make it more obvious to users wishing to make minor contributions
* Misc: some fixes to links …
> docs: homepage refresh

- cmd/adsysd/integration_tests/adsysctl_doc_test.go
- docs/explanation/index.md
- docs/explanation/proxy.md
- docs/how-to/index.md
- docs/how-to/set-up-adsys.md
- docs/how-to/set-up-adwatchd.md
- docs/how-to/use-gpo.md
- docs/reference/index.md
- docs/tutorial/index.md
* makes landing pages more consistent within the ADSys docs and compared to other Canonical documentation sets
* generally, tried to reduce complexity on landing pages, by removing unnecessary content, improving styling and adding brief explanatory text where appropriate
* moved supported releases info from reference landing page (buried) into ADSys how-to guide (surfaced)
* other minor fixups: sentence case for titles and avoid numeric digits <10 in text, in accordance with our style guide, and some spacing adjustments
* failing test was addressed by updating titles in the Go test for docs
UDENG-6054
> docs: landing pages refresh

- docs/.custom_wordlist.txt
- docs/custom_conf.py
- docs/how-to/set-up-ad.md
- docs/reference/glossary.md
- docs/reference/index.md
- docs/tutorial/certificates-auto-enrollment.md
Adds a reference glossary to the ADSys documentation, which may be especially useful for Windows sysadmins unfamiliar with Linux-specific terminology.
This work was a contribution from @davidekete through the Open Documentation Academy (thanks David!):
https://github.com/canonical/open-documentation-academy/issues/165
UDENG-6210
> docs: Add ref glossary

- debian/changelog
This release includes some needed fixes to the certificate auto-enrollment vendored code and to the GPO parser, which couldn't parse policy files larger than expected.
> Release 0.16.3

- go.mod
Fixes vulnerability #1: GO-2025-3563
Request smuggling due to acceptance of invalid chunked data in net/http
More info: https://pkg.go.dev/vuln/GO-2025-3563
> Bump toolchain to 1.23.8

- docs/.custom_wordlist.txt
- docs/explanation/index.md
- docs/explanation/security-overview.md
A security overview includes information about what relationship ADSys has to security, what factors influence its secure usage and what security documentation can be found to support its use.
* adds a security overview page
* updates explanation index
* updates wordlist
UDENG-6576
> docs: add security overview explanation

- docs/conf.py
- docs/requirements.txt
A sitemap improves search engine performance but is currently not available for the ADSys docs.
The changes in this PR generate a `sitemap.xml` when the docs site is built, e.g.,
It can be accessed at `https://documentation.ubuntu.com/adsys/{version}/sitemap.xml` after the PR is merged (note: won't be available in stable until next release).
It can also be previewed here: https://canonical-ubuntu-documentation-library--1263.com.readthedocs.build/adsys/1263/sitemap.xml
Similar changes are to be applied across all Canonical product documentation sites.
---
ps --- adding Samba docs to ignore list for linkcheck for now. The links work but are erroring, possibly due to request limits.
UDENG-7164
> docs: build sitemap for ADSys docs

- docs/.custom_wordlist.txt
- docs/reference/index.md
- docs/reference/release-notes.md
Adds release notes as a reference page to the documentation.
Notes include highlights from changelogs available on GitHub for recent releases.
This release notes page should be updated as future versions are released.
UDENG-8094
> docs: add release notes

- docs/conf.py
- docs/how-to/certificates-auto-enrollment.md
- docs/how-to/index.md
- docs/index.md
- docs/reference/features.md
- docs/tutorial/index.md
We now have a dedicated getting started tutorial to act as the single entry point for new users of ADSys.
The tutorial on certificate auto-enrollment was always more of a how-to guide, so we should move it into the how-to section.
This PR also includes some minor changes for wording, links, and redirects.
UDENG-7607
> docs: move certs tutorial to howto section
